/* 
- Curso: Programación Web 1
- Alumno: Manuel Alexander Ajanel Jerónimo
- Carné: 21791

----- HOJA DE TRABAJO SOBRE EJERCICIOS EN TYPESCRIPT -----

// EJERCICIO 1: CONCEPTOS BASICOS //
/* 
1. Declara una variable de tipo string y asígnale un valor.
2. Declara una variable de tipo number y asígnale un valor.
3. Declara una función que tome dos parámetros de tipo number y devuelva su suma.
*/

//1

let string: string = "Hola Mundo";

//2

let number: number = 5;

//3

function suma(a: number, b: number): number {
  return a + b;
}
